### ISSUE TITLE
AEBN agent cannot match when studio name or movie title has extra periods in it

### ISSUE THREAD

**Issue by hawkeyefla** [LGBT-PlexPlugins/plex-gay-metadata-agent#38]
For titles like Twinks Like It...Just Bareback it wants to search "twinks like it.."

Studios like "Bareback Inc." or "St. Louis Boy Toyz Movies" it won't match a file either, which could be loosely related to #37 since nothing matches without a studio name now.

**Comment by hawkeyefla** [comment]
Meant to mention, other various punctuation characters work just fine, it's only the .

**Comment by checktravis** [comment]
I ran into this as well. I wonder if a fuzzy match setting would solve? I.e. matching the beginning of the title instead of exact match of whole title.
