### ISSUE TITLE
AEBN has a critical error if the movie title exactly matches a series title

### ISSUE THREAD

**Issue by hawkeyefla** [LGBT-PlexPlugins/plex-gay-metadata-agent#39]
For movies like "Twinky Feet" "Reality First Time Sex" these are part of a named series on AEBN with a matching name for the series.

[AEBN title same as series.txt](https://github.com/iklier/plex-gay-metadata-agent/files/924018/AEBN.title.same.as.series.txt)

**Comment by vittsof** [comment]
No solution yet? It still does not recognize the first title of a series.
