### ISSUE TITLE
Having trouble with AEBN Matching when one title is shared by multiple studios

### ISSUE THREAD

**Issue by CodyBerenson** [LGBT-PlexPlugins/plex-gay-metadata-agent#47]
Hi folks,

I'm not super techy, so it may be me....  I'm having trouble with AEBN....when a title is unique, the match is GREAT!  When a title of a movie is used by more than one studio, it is unable to match or matches the wrong studio, regardless of how I name the file.  For example, the title "After Hours" from Lucas Entertainment is incorrectly matched to Daddy Oohhh! Productions...and I can't seem to find any combination of file naming to fix the match.  Help!?!  

Thanks so much in advance.  LOVE these plugins

**Comment by hawkeyefla** [comment]
Have you tried  (Lucas Entertainment) - After Hours
