### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by eyung71** [LGBT-PlexPlugins/plex-gay-metadata-agent#49]
I’ve recently downloaded the plugin and it’s installed correctly. I get matches to my titles but there’s no metadata or images coming down from any one of the sites. 
Is anyone further developing this plugin?

**Comment by MrPlow254** [comment]
You need to do bug reports. It works on my plex servers.

**Comment by eyung71** [comment]
How do I do a bug report? I have the most updated Mac plex media server app. I’ve installed the plugin correctly. The library is using the Gay Adult plugin. I have 1200 files. The files are carefully renamed to match the listed requirements. (Eg following instructions in here.) but so far no metadata from any of the sites comes down. It’s jusr making thumbnails from the videos themselves.

**Comment by MrPlow254** [comment]
I need log files, videos of the issue, screen shots. Whatever can actually get me information i need to see if its user error or code error. When you create an new issue that will contain information i need; I made a template that provides you with all information needed. Do not reply to this issue when you complete all the information I need. Please create a new one.

It is possible that the code is not working on Mac that is not something I am able to test. @iklier uses Mac I believe.
