### ISSUE TITLE
Issues retrieving metadata

### ISSUE THREAD

**Issue by JPH71** [LGBT-PlexPlugins/plex-gay-metadata-agent#54]
**What version of Plex Gay Metadata Agent are you reporting this for?** 
Latest - downloaded on 16 July 2019

**Describe the bug**
A clear and concise description of what the bug is
I have tried to download metadata for the following file name formats:
1.  (StudioName) - MovieName (Year).ext - failed
2.  (StudioName) - MovieName.ext - failed
3.  MovieName.ext - **Success**

The name of the movie was 
(All Worlds Video) - Bringing Out Brother (2002).mp4 - failed
(All Worlds Video) - Bringing Out Brother.mp4 - failed
Bringing Out Brother.mp4 - **Success**

I tried the same for (All Worlds Video) - Mitchell Rock Workin' It Out (2010).mp4 with the resultant success when I removed the Studio and Year

How can I get the agent to work for format 1. as all my movies are named like this and this obviously avoids cases where one could have duplicate names from two different studios?

I noticed that there is a Regex Setting for format 2 but this is not working, what do I need to do to get format 2 to work??

In relation to format 1 - is there a regex setting I can use once you have explained how I can get format 2 at minimum to work?

What section does it affect?
Movies

**Screenshots / Screen recordings**
Attached are screen shots of the agent setup
Note I am only using the AEBN bundle
![agent setup 1](https://user-images.githubusercontent.com/43102249/61340799-cf8a6080-a83b-11e9-9ff5-5a67129b4bb3.PNG)
![agent setup 2](https://user-images.githubusercontent.com/43102249/61340800-cf8a6080-a83b-11e9-98ef-d4954124cb54.PNG)
![agent setup 3](https://user-images.githubusercontent.com/43102249/61340801-d022f700-a83b-11e9-9ec5-399ff2e2d804.PNG)
![test library](https://user-images.githubusercontent.com/43102249/61340803-d022f700-a83b-11e9-9bfc-249e28a1b24d.PNG)
![test library 2](https://user-images.githubusercontent.com/43102249/61340943-5fc8a580-a83c-11e9-80c5-a41b0790af0b.PNG)

**Attached logs**
[com.plexapp.agents.aebn.log](https://github.com/LGBT-PlexPlugins/plex-gay-metadata-agent/files/3399702/com.plexapp.agents.aebn.log)
[com.plexapp.agents.cockporn.log](https://github.com/LGBT-PlexPlugins/plex-gay-metadata-agent/files/3399703/com.plexapp.agents.cockporn.log)

**Server / Test environment (please complete the following information):**
 - Physical Machine
 - Operating system Windows 10
 - Plex version 1.16.2.1297

**Comment by acvigue** [comment]
Hey. This repo isn't maintained. I mostly focus on Helix and site agents, but I can look into this on my repo

https://github.com/acvigue/pgma

**Comment by JPH71** [comment]
Hi Aiden

Thanks for pointing me to the new repo.

After a bit of investigation and scratching my head to bit in trying to
understand regex I came up with the following to complement my file naming
structure
(Studio Name) - Movie Title (Year).extension = *^\(((?P<studio>.+))\) -
(?P<clip_name>.+) \((?P<year>\d\d\d\d)\)*

This works brilliantly and gets most of the movies off AEBN, though not
always

I have 2 main issues:

First 1. Films in a series for example *(Hot House Entertainment) -
Reckless (2009)* and *(Hot House Entertainment) - Reckless 2 (2009)*

It will get the metadata for (Hot House Entertainment) - Reckless 2 (2009)
but not for the first in the series. When I look at the logs I get the
following error shown in this log file
*com.plexapp.agents.aebn-error1*


Second 2. Some films will download part of the metadata but will not change
the title of the movie in plex.. therefore I end up with the artwork but
the title will show as thus:

*(Treasure Island Media) - Legendary Stud - Brad McGuire (2008)* will come
up as *Treasure Island Media Legendary Stud Brad McGuire* instead of *Legendary
Stud: Brad McGuire*


My other issues are - if there is no date in AEBN how can I set the date to
be the January 1st of the year indicated in the filename?

For example *(Treasure Island Media) - Anonymous Sex (2016)* has no date
indicated on AEBN


Sorry to be a nuisance....

I have not got much scripting experience with python... I mainly script in
vbscript...

If you know of any information that would help me with writing a new plex
agent, I will be grateful...

Lastly is there a way to make the LGBT plex agent contribute to The Movie
Database and Plex Movie, so that if no data is found on AEBN or the other
sites it would go to TMDB like other agents to?

Kind Regards

Jason

**Comment by acvigue** [comment]
i have no idea how the AEBN agent works, I'll look into it as soon as I can. Could you make an issue in the other repo?
TMDB and Plex Movie don't typically accept adult content / nor is there a whole selection that even makes it worth it to write another agent.

**Comment by JPH71** [comment]
Hi Aiden
I will raise the issues in the other repo.
I think the main issue with the seven scrapper is that if it finds multiple
results it blows its top.

Cheers
Jason

**Comment by JPH71** [comment]
Hi Aiden

After a lot of struggles.. I have managed to create 4 agents that work on
the following sites
aebnii - adapted from previous one
gayhotmovies
gaydvdempire - adapted from the dvdempire
waybig.com

how do i upload them?

Kind regards

Jason

**Comment by acvigue** [comment]
https://github.com/LGBT-PlexPlugins/plex-gay-metadata-agent/issues/54#issuecomment-541227941
please create a pull request (on the new repo) or upload a ZIP file (with just your changes) to an issue there. i will test and if the tests succeed, i will merge the changes.

**Comment by JPH71** [comment]
Hi Aiden

I have uploaded the files. Many thanks..
Next site I want to scrape is Homoactive and maybe the new AEBN site layout
I will await your feedback and testing
