### ISSUE TITLE
Helix videos are not matching

### ISSUE THREAD

**Issue by Thisismygithubname1** [LGBT-PlexPlugins/plex-gay-metadata-agent#55]
**What version of Plex Gay Metadata Agent are you reporting this for?**
Tried with both the PR #53 version and latest master
**Describe the bug**
Helix videos are not matching

**To Reproduce**
Load in videos downloaded directly from Helix. Tried with both 8teenboy (which is Helix) and pure Helix files. File names are similar to: hx120_scene76_member_1080p
Left match pattern at default. Set match folder to * to be safe

**Expected behavior**
Expected match of filenames

**Screenshots / Screen recordings**

**Server / Test environment (please complete the following information):**
Synology DS415+ using Plex 1.16.1.1291
[plex.log](https://github.com/LGBT-PlexPlugins/plex-gay-metadata-agent/files/3400400/plex.log)

**Additional context**

**Comment by acvigue** [comment]
18teenboy is a seperate company (still associated with helix.) Use the EightTeenBoy agent to fetch those scenes.

**Comment by acvigue** [comment]
this will be fixed in a new update on the NEW repo.

**Comment by MrPlow254** [comment]
^(?P<clip_name>.+) searches by the name of the clip. nothing in "hx120_scene76_member_1080p" is the name of the clip.

"THICK DICKED" is a name of a clip. you can so the filename would need to be "THICK DICKED.mp4" or whatever.

But that being said the helix site had an update breaking the scraper. So it won't pull all the data correctly until its fixed.
