### ISSUE TITLE
AEBN Updated their Site; You'll need to make an update to __init__.py to get the scanner to continue to work

### ISSUE THREAD

**Issue by CodyBerenson** [LGBT-PlexPlugins/plex-gay-metadata-agent#56]
AEBN has introduced a "new" website.  Currently, they still make the "Classic View" available, but introduction of the new site has broken this plugin.  It is an easy fix:

1.  Make a copy of __init__.py  (in windows, it is in this location (or something close to) C:\Users\User\AppData\Local\Plex Media Server\Plug-ins\AEBN.bundle\Contents\Code

2.  Update 2 entries in #URLS:
a.  BASE_URL='http://gay-classic.aebn.com'
b.  BASE_SEARCH_URL='http://gay-classic.aebn.com/dispatcher/fts?userQuery=%s&searchType=movie&imageType=Small'

3.  Save the file.

4.  Stop PMS.  Restart it.

5.  The AEBN scanner should work again.  

I'm the least technical person alive.  Anyone can do this.  Hope this helps.  This is the best scanner ever.  Currently have 10009 indexed titles and counting.  :)

**Comment by CodyBerenson** [comment]
Update:  AEBN continues to tweak.  Here's the latest that works:

1.  Make a copy of init.py (in windows, it is in this location (or something close to) C:\Users\User\AppData\Local\Plex Media Server\Plug-ins\AEBN.bundle\Contents\Code

2.  Update 2 entries in #URLS:
a. BASE_URL='https://gay.theater.aebn.net'
b. BASE_SEARCH_URL='https://gay.theater.aebn.net/dispatcher/fts?userQuery=%s&theaterId=842&genreId=102&locale=en'

3.  Save the file.

4.  Stop PMS. Restart it.

5.  The AEBN scanner should work again.

I'm the least technical person alive. Anyone can do this. Hope this helps. This is the best scanner ever. Currently have 10009 indexed titles and counting. :)

I worrry that at some point, their site will stop providing metadata consumable by plex...

**Comment by fabutrash** [comment]
Hi @CodyBerenson 
I'm interested in this agent but have failed to get it to work, even after updating the init.py file. Is it still working for you?

Any ideas? I want to pretty up my library before sharing it with my friends.

Thanks!
