### ISSUE TITLE
no gay porn recognized on Synology 918+

### ISSUE THREAD

**Issue by AlexCGN13** [LGBT-PlexPlugins/plex-gay-metadata-agent#60]
Hi , 
I just tried to install Plex with the offrered adult Media agents, but Plex doesn't recognize any of my gay porn: 
I tried one example: i had Catalina - call boy.mp4 , with all the cockporn agents, Plex didn't recognize the file and didn't download the cover. 
I tried to deactivate all agents but AEBN, but Plex still didn't recognize the file. 

Does someone have any sugesstions?

**Comment by HauteNTX** [comment]
Your file is not formatted correctly for the agent to pick it up.

Ideally it should be as followes

(Studio Name) - Title (YYYY).   mp4

So your file should look like this

(Catalina) - Call Boy.mp4

I don’t believe the year matters that much but if you have multiple movies with same title (i.e. ‘The Hole’) then the year is important.

The AEBN scanner is also very particular, so make sure your title is how AEBN lists it.

Change the file name and drop it in a new library to test first.

Hope this helps.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlexCGN13** [comment]
Hi HauteNTX, 
Thanks for your advice, but I just retried with the studio name in brackets , and without studio name, but there still no jacket , only a screenshot appearing :-(
<img width="177" alt="Capture d’écran 2020-02-11 à 23 40 34" src="https://user-images.githubusercontent.com/41262722/74286518-36b3b900-4d28-11ea-8c9c-eb584d413d3d.png">

**Comment by AlexCGN13** [comment]
Hi Team, 
Hi HauteNTX, 
I Got the AEBN plugin to work with the  changes described in the issue.
Are there other plugins still working , or are the other ones all dead?
Hugs, 
Alex

**Comment by HauteNTX** [comment]
Alex,
For the most part the other scrapers are functional.  If you are looking for some new metadata tools, check out acvigue/pgma  on git hub.  It’s a fork of this scraper but has some new sources like gaydvdempire, way big, gay erotic video index, and an updated aebn (since the new aebn site breaks everything).

Check it out.  It’s constantly being updated.

Best,
HauteNTX

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlexCGN13** [comment]
Perfect, thank you! 
This project seems to be more actual! 
Greetings , 
Alex
