### ISSUE TITLE
Modernized/Current Agents

### ISSUE THREAD

**Issue by CodyBerenson** [LGBT-PlexPlugins/plex-gay-metadata-agent#61]
Hi Folks,

A terrific developer, @jph71 has developed a series of Plex Gay Metadata Agents for both Full Length Films from robust index sites (e.g., AEBN, Gay Erotic Video Index (GEVI), GayDVDEmpire, GayHotMovies, etc.) and Blogged Scenes (WayBig, QueerClick, and Fagalicious).  

Although the concept of studio specific indexes (Helix, Sean Cody, Cockyboys) aren't supported (studios often update their sites rendering Agents inoperable), the scenes from a lot of studios are blogged at WayBig, QueerClick, and Fagalicious etc., which also include very nice Poster images for the scenes).   

![scene](https://user-images.githubusercontent.com/40373801/76800955-076eec80-67ab-11ea-92c2-b67e4c4cfda3.jpg)

The agents can be found here:  https://github.com/CodyBerenson/PGMA-Modernized

**Comment by JPH71** [comment]
Looks well good!

**Comment by CodyBerenson** [comment]
@MrPlow254 

Hello Nick, hope this finds you well.  :)

Since this repository is a link in the plex forum, I was hoping that you would consider putting a link to our agents on the main page on this repository?  This way, folks can get to a robust set of working  and maintained agents?  Thanks for considering!

https://github.com/CodyBerenson/PGMA-Modernized

**Comment by MrPlow254** [comment]
I added a link to the read me.

**Comment by JPH71** [comment]
Nice!
